### ISSUE TITLE
FloatingActionButton中的Tooltip未正常显示

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#102]
`public class TestWidgets : UIWidgetsPanel
    {
        protected override void OnEnable()
        {
            FontManager.instance.addFont(Resources.Load<Font>("MaterialIcons-Regular"), "Material Icons");
            base.OnEnable();
        }

        protected override Widget createWidget()
        {
            return new MaterialApp(
                title: "Fullter Demo",
                theme: new ThemeData(primaryColor: Colors.deepOrange),
                home: new BottomAppBar_Demo()
                );
        }
    }

    public class BottomAppBar_Demo : StatefulWidget
    {
        public override State createState()
        {
            return new BottomAppBar_DemoState();
        }
    }

    class BottomAppBar_DemoState : State<BottomAppBar_Demo>
    {
        public override Widget build(BuildContext context)
        {
            return new Scaffold(
                floatingActionButton: new FloatingActionButton(
                    onPressed: () => { },
                    tooltip: "0123456789",
                    child: new Icon(Icons.add, color: Colors.deepOrange)
                    )
                );
        }
    }`

**Comment by kgdev** [comment]
应该可以了 你再试一下最新的code？

**Comment by liusujin** [comment]
现在正常了.
