### ISSUE TITLE
升级到 Unity 2019.1.0f1 后代码报错

### ISSUE THREAD

**Issue by VDerGoW** [UnityTech/UIWidgets#104]
报错的代码文件：
`\Tests\Editor\CanvasAndLayers.cs`
报错的代码行：
`第71行：this.SetAntiAliasing(4);`

扩展方法的命名空间发生了变化，不再是实验性的了。

![image](https://user-images.githubusercontent.com/11539008/55844742-565edb80-5b71-11e9-97fa-7efa9a07a931.png)
![image](https://user-images.githubusercontent.com/11539008/55844878-0af8fd00-5b72-11e9-89e2-d4b1ee85b5a8.png)

**Comment by kgdev** [comment]
https://github.com/UnityTech/UIWidgets/pull/105
