### ISSUE TITLE
屏幕不会自动刷新

### ISSUE THREAD

**Issue by SNekyra** [UnityTech/UIWidgets#108]
在不加摄像头的情况下屏幕不会自动刷新，屏幕很容易变糊

**Comment by kgdev** [comment]
能具体一点吗？

**Comment by kgdev** [comment]
加一些截图

**Comment by SNekyra** [comment]
[cid:image011.png@01D4EFBB.21920ED0][cid:image012.png@01D4EFBB.21920ED0][cid:image013.png@01D4EFBB.21920ED0][cid:image014.png@01D4EFBB.21920ED0][cid:image015.png@01D4EFBB.21920ED0]
就是这种情况，在不开摄像机的情况下使用UIWidgets会留下残影

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: kgdev<mailto:notifications@github.com>
发送时间: 2019年4月10日 16:29
收件人: UnityTech/UIWidgets<mailto:UIWidgets@noreply.github.com>
抄送: Nero<mailto:wjsatan@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [UnityTech/UIWidgets] 屏幕不会自动刷新 (#108)


加一些截图

―

**Comment by SNekyra** [comment]
收到了？

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
From: jishu wang
Sent: Wednesday, April 10, 2019 4:33:38 PM
To: UnityTech/UIWidgets
Subject: 答复: [UnityTech/UIWidgets] 屏幕不会自动刷新 (#108)

[cid:image011.png@01D4EFBB.21920ED0][cid:image012.png@01D4EFBB.21920ED0][cid:image013.png@01D4EFBB.21920ED0][cid:image014.png@01D4EFBB.21920ED0][cid:image015.png@01D4EFBB.21920ED0]
就是这种情况，在不开摄像机的情况下使用UIWidgets会留下残影

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: kgdev<mailto:notifications@github.com>
发送时间: 2019年4月10日 16:29
收件人: UnityTech/UIWidgets<mailto:UIWidgets@noreply.github.com>
抄送: Nero<mailto:wjsatan@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [UnityTech/UIWidgets] 屏幕不会自动刷新 (#108)


加一些截图

―

**Comment by kgdev** [comment]
你到github上来贴吧...
