### ISSUE TITLE
触摸板ontap无效，其它没测。

### ISSUE THREAD

**Issue by duang2duang** [UnityTech/UIWidgets#116]
ugui正常，应该不是unity的问题。

**Comment by duang2duang** [comment]
AssertionError: Exception of type 'Unity.UIWidgets.foundation.AssertionError' was thrown.
Unity.UIWidgets.gestures.PointerEventConverter+<expand>d__2.MoveNext () (at Packages/com.unity.uiwidgets/Runtime/gestures/converter.cs:74)
Unity.UIWidgets.gestures.GestureBinding._handlePointerDataPacket (Unity.UIWidgets.ui.PointerDataPacket packet) (at Packages/com.unity.uiwidgets/Runtime/gestures/binding.cs:25)
Unity.UIWidgets.editor.WindowAdapter+<>c__DisplayClass25_0.<postPointerEvents>b__0 () (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:224)
Unity.UIWidgets.editor.WindowAdapter.withBinding (System.Action fn) (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:233)
Unity.UIWidgets.editor.WindowAdapter.postPointerEvents (System.Collections.Generic.List`1[T] data) (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:224)
Unity.UIWidgets.editor.WindowAdapter.postPointerEvent (Unity.UIWidgets.ui.PointerData data) (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:228)
Unity.UIWidgets.engine.UIWidgetsPanel.OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData) (at Packages/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs:250)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerDownHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:36)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by kgdev** [comment]
你说的触摸板是什么环境？大概的重现步骤是怎样的？

**Comment by duang2duang** [comment]
使用笔记本开发的时候用触摸板点击没效果，用的GestureDetector包装一个text。还有每次双击的时候会抛出一个错误：
AssertionError: Exception of type 'Unity.UIWidgets.foundation.AssertionError' was thrown.
Unity.UIWidgets.gestures.PointerEventConverter+<expand>d__2.MoveNext () (at Packages/UIWidgets-master/Runtime/gestures/converter.cs:74)
Unity.UIWidgets.gestures.GestureBinding._handlePointerDataPacket (Unity.UIWidgets.ui.PointerDataPacket packet) (at Packages/UIWidgets-master/Runtime/gestures/binding.cs:25)
Unity.UIWidgets.editor.WindowAdapter+<>c__DisplayClass29_0.<postPointerEvents>b__0 () (at Packages/UIWidgets-master/Runtime/editor/editor_window.cs:248)
Unity.UIWidgets.editor.WindowAdapter.withBinding (System.Action fn) (at Packages/UIWidgets-master/Runtime/editor/editor_window.cs:257)
Unity.UIWidgets.editor.WindowAdapter.postPointerEvents (System.Collections.Generic.List`1[T] data) (at Packages/UIWidgets-master/Runtime/editor/editor_window.cs:248)
Unity.UIWidgets.editor.WindowAdapter.postPointerEvent (Unity.UIWidgets.ui.PointerData data) (at Packages/UIWidgets-master/Runtime/editor/editor_window.cs:252)
Unity.UIWidgets.engine.UIWidgetsPanel.OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData) (at Packages/UIWidgets-master/Runtime/engine/UIWidgetsPanel.cs:267)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerDownHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:36)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by yczhangsjtu** [comment]
你的实现大概是这样的吗？
new GestureDetector(
    onTap: () => {
        Debug.Log("Tapped");
    },
    onDoubleTap: (value) => {
        Debug.Log("Double Tapped");
    },
    child: new Text("Test")
)
这个我在Mac上试着没有问题
