### ISSUE TITLE
建议遵循C#语言的一般命名规则

### ISSUE THREAD

**Issue by Zoranner** [UnityTech/UIWidgets#125]
C#开发者表示看到JavaScript/Dart命名风格很难受🤐，其实是不习惯，每次更新后都要把脚本统一处理一遍。入乡随俗希望理解谢谢🙏。 还有#36 提到的问题也望重视。

P.S. 只是一个小小小建议，如果能的话更好，再次对开发者的贡献表示感谢。

**Comment by AhrenLi** [comment]
强烈支持

**Comment by zhuxingwei** [comment]
为了使项目能够持续track flutter的最新更新，以便给开发者们带来最好的开发体验，在可预期的将来我们还不打算改变项目的代码风格。不过，可能在项目这边完成一套自动化的dart 转 c#的编译pipeline后我们会考虑可能支持上述feature。多谢您的支持和理解！
