### ISSUE TITLE
请重视C#的风格规范

### ISSUE THREAD

**Issue by SanErClark** [UnityTech/UIWidgets#146]
写C#的程序猿都有洁癖，请开发者再三斟酌，这会影响框架的未来发展。

**Comment by kgdev** [comment]
嗯嗯。明白，我们也斟酌良久。结论是C#于Unity类似JS于Chrome，就是个脚本引擎。而且Unity的C#库里面大小写也不同意。所以决定沿用Flutter/Dart的风格。
