### ISSUE TITLE
flutter 的示例转不过来

### ISSUE THREAD

**Issue by liangxieq** [UnityTech/UIWidgets#147]
https://book.flutterchina.club/chapter6/scroll_controller.html 中的第一个示例报错
https://book.flutterchina.club/chapter6/custom_scrollview.html 中的示例报了很多断言错误

**Comment by kgdev** [comment]
能否把具体错误列出来

**Comment by zhuxingwei** [comment]
hi，抱歉这么晚才回复。经测试目前最新的稳定版（release_1.5.4) 中第一个示例已经不会报错了。经过测试，第二个示例报错的原因是原帖子中Colors.cyan等的写法有些问题，导致访问了不存在的Key。经过修改后也没有问题。具体测试Sample可参考https://github.com/zhuxingwei/UIWidgetsSample/blob/master/TestIssue147Sample.cs。谢谢！

**Comment by liangxieq** [comment]
好的 谢谢
