### ISSUE TITLE
Stack内通过Positioned调整图片位置时，超出边界时会有问题。谢谢！

### ISSUE THREAD

**Issue by jiangzhen3s** [UnityTech/UIWidgets#161]
new Unity.UIWidgets.widgets.Stack(
                                    alignment: Alignment.topLeft,
                                    children: new List<Widget> {
                                        Image.asset("a"),
                                        new Positioned(
                                            child:
                                                new GestureDetector(
                                                    onPanUpdate:details=>{
                                                        setState(()=>{
                                                            left += details.delta.dx;
                                                            top += details.delta.dy;
                                                        });
                                                        print(details);
                                                    },
                                                    child:Image.asset("b"))
                                            ,left:left,top:top)
                                    }
                                ),

![image](https://user-images.githubusercontent.com/317738/57005436-b0037480-6c0a-11e9-8f58-905c13b9002e.png)
![image](https://user-images.githubusercontent.com/317738/57005458-d1fcf700-6c0a-11e9-9b05-9f42de8bd00c.png)

**Comment by yczhangsjtu** [comment]
你好，参照您的代码，并没有复现这个问题。能不能提供一下更完整的环境？

public class TmpWidget : StatefulWidget
    {
        public TmpWidget(Key key = null) : base(key)
        {
        }

        public override State createState()
        {
            return new TmpWidgetState();
        }
    }

    class TmpWidgetState : State<TmpWidget>
    {
        private float left = 0, top = 0;

        public override Widget build(BuildContext context)
        {
            return new Stack(
                alignment: Alignment.topLeft,
                children: new List<Widget>
                {
                    Image.asset("ali_landscape"),
                    new Positioned(
                        child: new GestureDetector(
                            onPanUpdate: details =>
                            {
                                setState(() =>
                                {
                                    left += details.delta.dx;
                                    top += details.delta.dy;
                                });
                                Debug.Log(details);
                            },
                            child: Image.asset("unity-black", width: 200, height: 200)
                        ),
                        left: left,
                        top: top
                    )
                }
            );
        }
    }

<img width="595" alt="屏幕快照 2019-05-05 下午4 02 04" src="https://user-images.githubusercontent.com/10370154/57190655-5a530300-6f4f-11e9-8f26-15aea314b7fe.png">
<img width="591" alt="屏幕快照 2019-05-05 下午4 02 35" src="https://user-images.githubusercontent.com/10370154/57190656-676ff200-6f4f-11e9-9b77-87cc0b18a691.png">

**Comment by jiangzhen3s** [comment]
hi 你好 谢谢回复。

对比了下我的代码，我发现如果 Stack 又是其他布局的一部分时 就会触发这个问题。
在**editor**中运行会有问题，发布到**手机（测试了安卓）**上却没有。

以下我在TmpWidget 上又进行一次布局：

    class ExampleApp : StatefulWidget
    {
        public ExampleApp(Key key = null) : base(key)
        {
        }

        public override State createState()
        {
            return new ExampleState();
        }
    }

    class ExampleState : State<ExampleApp>
    {
        int counter = 0;
        public override Widget build(BuildContext context)
        {
            return
                new Padding(
                    padding: EdgeInsets.all(10),
                    child:
                      new Column(
                          children:
                              new List<Widget> {
                                new TmpWidget(),
                                new Text("Counter: " + this.counter, style: new TextStyle(color: Color.white)),
                              }
                      )
                );
        }
    }


![image](https://user-images.githubusercontent.com/317738/57191993-33e89400-6f5e-11e9-99b2-a64f6e78835f.png)

**Comment by yczhangsjtu** [comment]
我这边依然没有复现。代码完全相同的，效果是小图片被遮住了

<img width="359" alt="屏幕快照 2019-05-05 下午6 08 03" src="https://user-images.githubusercontent.com/10370154/57192244-e588c480-6f60-11e9-803e-984711ca99a2.png">
<img width="351" alt="屏幕快照 2019-05-05 下午6 09 23" src="https://user-images.githubusercontent.com/10370154/57192251-f0435980-6f60-11e9-8b2e-86fdc75727e9.png">
