### ISSUE TITLE
UIWidgets on iOS wouldn't respect "StatusBar Hidden" property

### ISSUE THREAD

**Issue by JustinFincher** [UnityTech/UIWidgets#163]
The previous version of UIWidgets used to handle the top insets (or safe area) well, but in recent commits, the support seems to be gone. Now a UIWdgets based project with StatusBar Hidden property false would produce the result below:
![IMG_0097](https://user-images.githubusercontent.com/8359912/57187903-96bf3880-6f28-11e9-92ee-6ac74ce84364.PNG)
Notice the status bar overlapped with UIWidgets panel while the native iOS app on the right would have a proper top insets 🤔

EDIT:
commit 7f000960a7c6fac057a491403acc0ba1b80354a2  
Unity version 2018.3.12 & 2018.3.14

**Comment by zhuxingwei** [comment]
This problem is caused by: 
(1) create your App using the Scaffold Widget;
(2) leave the AppBar = null in the Scaffold;

To solve this problem, please ensure that the Body of your Scaffold is wrapped with a SafeArea Widget
