### ISSUE TITLE
interaction issue when overlapping an UIWidget panel on an UGUI panel

### ISSUE THREAD

**Issue by zhuxingwei** [UnityTech/UIWidgets#177]
When an UIWidget panel is overlapped on an UGUI panel, the UIWidget panel may stop the Graphics.Raycast to hit on the UGUI panel, even if it is totally transparent. 

Inspired by this work https://blog.csdn.net/weixin_33832340/article/details/87411208, We believe there are two possible ways to fix this issue:

(1) On the UIWidget framework, we make UIWidgetPanel an ICanvasRaycastFilter and test the raycasted pixel's alpha on the UIWidgetPanel.texture (NEED TO BLIT TO A TEXTURE2D FIRST, REQUIRING GPU-CPU TRAFFIC, THEREFORE QUITE LAGGY), to determine whether we should leave this raycast to UGUI or not.

(2) Users attach their own ICanvasRaycastFilter Component to the Panel and design a static Texture2D texture to best fit their UI layouts (NO NEED FOR GPU-CPU TRAFFICS)

Before overcoming the performance problem referred in method (1),  method (2) is suggested.

**Comment by liusujin** [comment]
目前使用第二种方法解决的，测试了下目前还没有较大的性能影响，之前主要问题是RenderTexture转换为Texture2D，期待更好的解决方案。

**Comment by zhuxingwei** [comment]
嗯嗯，多谢关注！这个问题已经在我们下一个里程碑的目标里了。目前已经一些比较好的idea了，敬请期待！
