### ISSUE TITLE
Android - Didn't find class "com.unity.uiwidgets.plugin.UIWidgetsMessageManager"

### ISSUE THREAD

**Issue by tsuixl** [UnityTech/UIWidgets#186]
Window Unity 2018.3.12 (Android 模拟器)

05-11 16:42:10.362  5603  5618 E Unity   :      at dalvik.system.
05-11 16:42:10.390  5603  5603 I Unity   : windowFocusChanged: false
05-11 16:42:10.390  5603  5603 I Unity   : onPause
05-11 16:42:10.398  5603  5618 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager
05-11 16:42:10.398  5603  5618 E Unity   : java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager
05-11 16:42:10.398  5603  5618 E Unity   :      at java.lang.Class.classForName(Native Method)
05-11 16:42:10.398  5603  5618 E Unity   :      at java.lang.Class.forName(Class.java:400)
05-11 16:42:10.398  5603  5618 E Unity   :      at java.lang.Class.forName(Class.java:326)
05-11 16:42:10.398  5603  5618 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
05-11 16:42:10.398  5603  5618 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source)
05-11 16:42:10.398  5603  5618 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
05-11 16:42:10.398  5603  5618 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:392)
05-11 16:42:10.398  5603  5618 E Unity   :      at android.os.Looper.loop(Looper.java:136)
05-11 16:42:10.398  5603  5618 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
05-11 16:42:10.398  5603  5618 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unity.uiwidgets.plugin.UIWidgetsMessageManager" on path: DexPathList[[zip file "/data/app/com.Test.TestWidgets-1/base.apk"],nativeLibraryDirectories=[/data/app/com.Test.TestWidgets-1/lib/x86, /data/app/com.Test.TestWidgets-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]

代码是UIWidgetsExample.cs. 
请问这个要如何解决?

**Comment by zhuxingwei** [comment]
hi，我使用实机以及Android Studio的自带模拟器运行UIWidgetExample对应的UI，并没有出现上述问题。麻烦您确认一下：（1）您的模拟器是否是通用的Android手机模拟器？（2）您的模拟器版本？

如果您使用通用模拟器（例如上面提到的我们测试使用的Android Studio自带模拟器）仍然出现了上述报错，烦请告知我们具体出错配置（例如Android SDK Level，机型等）。

多谢！

**Comment by tsuixl** [comment]
模拟器 Nexus 5X API 25 (x86)
这个问题在其他设备同样在,所以我猜测可能是工程或是打出的Apk有问题.

项目以及工程地址
链接：https://pan.baidu.com/s/1q4hyzuWsDW1mjiRp-divcw 
提取码：7p98 

感谢帮助.

![Alt text](https://i.bmp.ovh/imgs/2019/05/e835660f11c97016.jpg)
![Alt text](https://i.bmp.ovh/imgs/2019/05/0d5cb08bd5ded5f2.png)
![Alt text](https://i.bmp.ovh/imgs/2019/05/fee1edd3195c301c.png)
![Alt text](https://i.bmp.ovh/imgs/2019/05/9b90f4cbdb8ae6a6.png)

**Comment by tsuixl** [comment]
BuildSystem -> Internal 有问题,使用BuildSystem -> Gradle ()正常
