### ISSUE TITLE
能否将这个插件发布到UnityAssetStore？

### ISSUE THREAD

**Issue by suntabu** [UnityTech/UIWidgets#188]
发布到UnityAssetStore有许多好处：
1. 能引起更多的关注，
2. 其他开发者能基于这个插件开发其他组件，我现在写了一个markdown renderer，但是没有办法引用该插件导致不能上线，
3. 更加方便的引入到工程。

**Comment by kgdev** [comment]
好 收到！

**Comment by Latias94** [comment]
https://assetstore.unity.com/packages/tools/gui/uiwidgets-146398
