### ISSUE TITLE
使用RefreshIndicator包装listview，已经接收了http，为啥还一直播放刷新动画？

### ISSUE THREAD

**Issue by huangyingran** [UnityTech/UIWidgets#194]

**Comment by yczhangsjtu** [comment]
你好，能不能给一下代码的示例？

**Comment by huangyingran** [comment]
> 你好，能不能给一下代码的示例？

  Promise OnRefresh()
        {
            return new Promise((action, action1) =>
            {
                
                Debug.Log("begin");
                HTTPRequest request = new HTTPRequest(new Uri(Api.getProductMetasByCategoryType),HTTPMethods.Post,(delegate(HTTPRequest originalRequest, HTTPResponse response) {

                    if (response.IsSuccess)
                    {
                        ResultVo<List<ProductMeta>> resultVo = JsonMapper.ToObject<ResultVo<List<ProductMeta>>>(response.DataAsText);
                        action=delegate { SetProductMetas(resultVo, context);};
                        action();
                    }
                  }));
                request.AddField("categoryType","0");
                request.AddField("page","0");
                request.AddField("size","10");
                request.AddField("sortKey","productCreateTime");
                request.Send();
               // action1= delegate(Exception exception) { new Exception("faile"); };
                action1(new Exception("faile"));
            });
        }
        

        public override Widget build(BuildContext context)
        {
            return new RefreshIndicator(
                onRefresh: OnRefresh,
                displacement: 40,
                child: ListView.builder(
                    controller: _controller,
                    itemCount: _productMetas.Count,
                    itemBuilder: _rendrow
                )
            );
        }

**Comment by yczhangsjtu** [comment]
好的，我会尽快看一下~

**Comment by yczhangsjtu** [comment]
action=delegate { SetProductMetas(resultVo, context);};
这一行是不是把传递进来的action覆盖了？

**Comment by huangyingran** [comment]
> action=delegate { SetProductMetas(resultVo, context);};
> 这一行是不是把传递进来的action覆盖了？

有没有你们的例子？谢谢，我改了好久了都没成。

**Comment by yczhangsjtu** [comment]
> > action=delegate { SetProductMetas(resultVo, context);};
> > 这一行是不是把传递进来的action覆盖了？
> 
> 有没有你们的例子？谢谢，我改了好久了都没成。

onRefresh什么都没有做的例子。
```
private List<string> items = new List<string> {"First", "Second", "Third"};

        public override Widget build(BuildContext context)
        {
            return new Stack(
                children: new List<Widget>
                {
                    new Scaffold(
                        body: new RefreshIndicator(
                            child: ListView.builder(
                                itemCount: items.Count,
                                itemBuilder: (BuildContext _, int index) =>
                                {
                                    string item = items[index];
                                    return new ListTile(
                                        isThreeLine: true,
                                        leading: new Text(item),
                                        title: new Text($"This item represents {item}."),
                                        subtitle: new Text(
                                            "Even more additional list item information appears on line three.")
                                    );
                                }
                            ),
                            onRefresh: () => { return new Promise((action, action1) =>
                            {
                                action();
                            }); }
                        )
                    ),
                    new PerformanceOverlay()
                }
            );
        }
```

**Comment by yczhangsjtu** [comment]
找到原因了，UIWidget没有处理出错的情况，正在修复~

**Comment by huangyingran** [comment]
好的

**Comment by yczhangsjtu** [comment]
> 好的

已经修复好了，再试一下~
