### ISSUE TITLE
Is it preview or not?

### ISSUE THREAD

**Issue by akihikodaki** [UnityTech/UIWidgets#215]
I found UIWidgets on Asset Store, which doesn't say it is 1.0.0. However, Its unity package on packages.unity.com says it is 1.0.2-preview. Should I consider the version on Asset Store is ready for production but one on packages.unity.com is not yet?

Thank you for this awesome work.

**Comment by zhuxingwei** [comment]
No, the UIWidgets package is still in its "preview" stage. We are still working on polishing this project and add more features to it. 

However, we believe UIWidgets already contains all the basic functionalities for you to build your projects now. Feel free to try it on and your advices are always the most appreciated !

**Comment by akihikodaki** [comment]
Thnak you for your answer. I will close this issue.
