### ISSUE TITLE
How to update the widgets externally from MonoBehaviour?

### ISSUE THREAD

**Issue by lincode** [UnityTech/UIWidgets#238]
For example, I fire a bullet to destroy a monster then I need to update the the score on the panel implemented with UIWidgets. How to talk with UIWidgets from MonoBehaviour?

It will be very nice to add this example.

**Comment by zhuxingwei** [comment]
hi, thanks for your question! 
In UIWidgets, an UIWidgetsPanel object can be forced to repaint by calling the function **recreateWidget**. 
As to the scenario in your given example, you can make your widget, e.g., ScoreboardWidget listen to the score change event. Whenever the score changes, you can call some logic like `this.recreateWidget()` on the widget itself to refresh the UI according to the new score value.

**Comment by KABBOUCHI** [comment]
you can use `ChangeNotifier`
```c#
public class ModelTest : ChangeNotifier
{
   private int _number;
   public int Number
   {
      get
       {
         return _number;
       }
      set
      {
         _number = value;
          this.notifyListeners();
      }
   }
}
```

```c#
// in UIWidgetsPanel script
ModelTest model = new ModelTest();

// from Unity main thread
using (window.getScope())
{
    model.Number++;
}
```
