### ISSUE TITLE
GestureDectore 未实现onLongPressUp事件

### ISSUE THREAD

**Issue by coollemen** [UnityTech/UIWidgets#245]
onLongPress能够正常触发 ，但是onLongPressUp不行，是不是没有实现onLongPressUp事件啊？还有onTapDown触发后，马上释放可以触发onTapUp，如果按的久一点就无法触发onTapUp事件。（是在编辑器模式下用鼠标测试的，window和mac下都有同样问题，难道要真机才能触发吗？）

**Comment by zhuxingwei** [comment]
（1）onLongPressUp已经支持，多谢捉虫：） #246 ；（2）这个问题我在Editor里无法复现。试过长按20秒再松手，也无法触发。测试代码如下：
`public override Widget build(BuildContext context) {
            return new GestureDetector(
                onTapDown: (value) => { Debug.Log("11111111");},
                onTapUp: (value) => {Debug.Log("222222");},
                child: new Center(
                    child: new Container(
                        width: 200,
                        height: 200,
                        color: Colors.blue
                    )
                )
            );
        }`
