### ISSUE TITLE
Chip删除按钮点击效果异常

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#256]
长按Chip的删除按钮时，出现图示的效果
![image](https://user-images.githubusercontent.com/19631892/61519289-1e9fe380-aa3e-11e9-83c8-12d778a49299.png)，

**Comment by liusujin** [comment]
代码：
private List<Widget> CreateChips()
        {
            List<Widget> chips = new List<Widget>();
            foreach (DepartmentConfig config in this.Configs.FindAll(p => p.Type == "Section"))
            {
                chips.Add(new Chip(
                    label: new Text(config.Name),
                    onDeleted: () => { },
                    deleteIcon: new Icon(Icons.clear, color: Colors.red),
                    padding: EdgeInsets.only(5, 5, 15, 5),
                    shape: new RoundedRectangleBorder(
                        borderRadius: BorderRadius.all(20)
                        )
                    ));
            }
            return chips;
        }

**Comment by liusujin** [comment]
unity版本：2018.4.2f1

**Comment by yczhangsjtu** [comment]
请问图示效果指的是长按之后弹出一个红色框吗？

**Comment by liusujin** [comment]
截图失误，红色框为无关布局显示，异常效果是指长按删除按钮时水波纹效果为被chip的边框正确裁剪

**Comment by zhuxingwei** [comment]
> 截图失误，红色框为无关布局显示，异常效果是指长按删除按钮时水波纹效果为被chip的边框正确裁剪

这个问题在最新的master版本中已经修复了。多谢捉虫！！

**Comment by liusujin** [comment]
> > 截图失误，红色框为无关布局显示，异常效果是指长按删除按钮时水波纹效果为被chip的边框正确裁剪
> 
> 这个问题在最新的master版本中已经修复了。多谢捉虫！！

这个问题确认了下已经被修复了，还有个问题不确定是否为Bug，在Windows编辑器下InputChip显示效果异常如下：
![TIM](https://user-images.githubusercontent.com/19631892/63840298-686fd800-c9b3-11e9-9e91-44e37c145a72.jpg)
，去除UIWidgets_DEBUG宏后显示正常
![image](https://user-images.githubusercontent.com/19631892/63840486-b84e9f00-c9b3-11e9-8f0c-251c41282f0e.png)，希望能告知下这是设计如此方便调试还是显示问题，谢谢！

**Comment by zhuxingwei** [comment]
嗯嗯，是Debug信息。我们稍微fix了一下 #300 ，现在一般情况下不会再出现这个Debug Paint了。多谢！

**Comment by liusujin** [comment]
没问题了，期待之后的正式版！
