### ISSUE TITLE
来自Xamarin社区，请教一下

### ISSUE THREAD

**Issue by Jddl** [UnityTech/UIWidgets#274]
我想问一下，你们从flutter转过来，是实现了Dart到C#的转换吗，否则如何移植这么大的代码量？
谢谢！

**Comment by kgdev** [comment]
现在是手写 没有那么多

**Comment by zjuwjf** [comment]
> 现在是手写 没有那么多

能请教 用C# 重写flutter-framework 需要花多长时间么？
