### ISSUE TITLE
什么时候会发布正式版，以及相关文档发布有计划吗？

### ISSUE THREAD

**Issue by eangulee** [UnityTech/UIWidgets#294]

**Comment by eangulee** [comment]
提问关于正式版发布的问题。

**Comment by zhuxingwei** [comment]
hi eangulee，多谢你的关注！我们会在本月底的milestone结束后release一个新的正式版本。该版本在性能优化、组件完成度上都会得到显著提升。UI Widgets目前已经支持了包含UnityConnect App在内的多个线上发布项目的制作，我们开发小组也会继续跟进bug fix并设计添加更多新的feature：开发者现在就可以放心使用它来构建你的应用。相关文档的整理工作我们在下一个milestone就会启动。具体发布时间表很快也会确定下来。届时我们会再做说明的。

**Comment by zhuxingwei** [comment]
hi，release 1.5.4目前已经available：）
