### ISSUE TITLE
关于BackdropFilterWidget的使用问题

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#304]
1.Windows10编辑器2018.4.8f1通过PackageManager下载的UIWidgets中使用BackdropFilter时模糊效果未正常出现。代码如下：
`public class BackgroundBlurWidget : UIWidgetsPanel
    {
        protected override Widget createWidget()
        {
            return new MaterialApp(
                home: new Stack(
                children: new List<Widget>
                {
                    new ConstrainedBox(
                        constraints:BoxConstraints.expand(),
                        child:Unity.UIWidgets.widgets.Image.network("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1545738629147&di=22e12a65bbc6c4123ae5596e24dbc5d3&imgtype=0&src=http%3A%2F%2Fpic30.photophoto.cn%2F20140309%2F0034034413812339_b.jpg")
                        ),
                    new Center(
                        child:new ClipRect(
                            child:new BackdropFilter(
                                filter:ImageFilter.blur(50f,50f),
                                child:new Opacity(
                                    opacity:0.5f,
                                    child:new Container(
                                        width:500,
                                        height:500,
                                        decoration:new  BoxDecoration(
                                            color:Colors.grey.shade200
                                            ),
                                        child:new Center(
                                            child:new Text(
                                                "Blur"
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                }
                )
                );
        }
    }`

2.BackdropFilter是否支持对UI和场景的模糊，目前看只支持对UI的模糊支持。

**Comment by zhuxingwei** [comment]
hi 多谢你的帮助！
（1）目前master分支上确实存在backdrop的模糊效果失效的BUG。该BUG已经在dev分支上修复了，你可以试一下？fix相关代码会等这周晚些时候QA完成后merge到master
（2）是的，目前backdrop只会对UIWidgets中的UI组件进行模糊。从工作优先级考虑，我们暂时还不支持、且近期也不会提供对场景模糊的支持。十分抱歉！

**Comment by liusujin** [comment]
好的，谢谢！
