### ISSUE TITLE
不能正常输入中文（Win10微软拼音输入法）

### ISSUE THREAD

**Issue by VDerGoW** [UnityTech/UIWidgets#31]
**系统环境**：Windows 10 64位专业版
**软件环境**：Unity 2018.3.5f1
**问题描述**：新建工程后，直接导入当前版本的UIWidgets包，在附带的测试场景（`Samples/UIWidgetSample/TextInput`）中，不能使用**微软拼音输入法**正常输入中文。而且有时候在某个文本框输入中文，不能提交到文本框，但是在点击了其他文本框之后，会将之前输入的内容提交到后点击的那个文本框。

**Comment by VDerGoW** [comment]
问题在编辑器和Build出来的PC可执行程序中都有发生，其他平台没有测试。

**Comment by fzhangtj** [comment]
你好，我这边在win 10测试了下Sample 里的TextInput ，是可以用**微软拼音输入法**输入和显示的。请问你用最新的代码还有这个问题吗？

**Comment by VDerGoW** [comment]
@fzhangtj 你好，刚才测试了一下，可以输入中文了，应该没问题了。
