### ISSUE TITLE
使用UIWidgets开发桌面应用的透明UI穿透问题

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#314]
在开发桌面应用过程中，全屏透明UI中边缘为按钮、清单等Widgets,中间部分属于透明UI，是否可以将透明部分的点击事件等穿透传递下去来达到点击场景物体的目的，目前思路是在UIWidgetsPanel的事件处理函数中检测当前点击位置的像素颜色，低于阈值则将事件传递下去，但是目前在获取其texture转为texture2D后像素点的颜色始终为0XCDCDCDCD,能否提供一些帮助？

**Comment by zhuxingwei** [comment]
using Unity.UIWidgets.engine;
using UnityEngine;
using UnityEngine.UI;
 
[DisallowMultipleComponent]
[RequireComponent(typeof(UIWidgetsPanel))]
public class UIWidgetsRaycastFilter : MonoBehaviour, ICanvasRaycastFilter
{
    public bool reversed;
 
    private UIWidgetsPanel rawImage;
 
    void OnEnable()
    {
        rawImage = GetComponent<UIWidgetsPanel>();
    }
    
    
    public static Texture2D toTexture2D(RenderTexture rTex)
    {
        Texture2D tex = new Texture2D(rTex.width, rTex.height, TextureFormat.RGBA32, false);
        RenderTexture.active = rTex;
        tex.ReadPixels(new Rect(0, 0, rTex.width, rTex.height), 0, 0);
        tex.Apply();
        return tex;
    }
 
    public bool IsRaycastLocationValid(Vector2 screenPoint, Camera eventCamera)
    {
        if (!enabled)
            return true;

        Texture2D texture = null;
        var w = rawImage.texture;
        texture = toTexture2D(w as RenderTexture);
        if (texture == null)
            return true;
 
        Vector2 local;
        RectTransformUtility.ScreenPointToLocalPointInRectangle(rawImage.rectTransform, screenPoint, eventCamera, out local);
 
        Rect rect = rawImage.rectTransform.rect;
 
        // Convert to have lower left corner as reference point.
        local.x += rawImage.rectTransform.pivot.x * rect.width;
        local.y += rawImage.rectTransform.pivot.y * rect.height;
 
        Rect uvRect = rawImage.uvRect;
        float u = local.x / rect.width * uvRect.width + uvRect.x;
        float v = local.y / rect.height * uvRect.height + uvRect.y;
        
        Debug.Log("alpha = " + texture.GetPixelBilinear(u, v).a);
 
        try
        {
            if (!reversed)
                return texture.GetPixelBilinear(u, v).a != 0;
            else
                return texture.GetPixelBilinear(u, v).a == 0;
        }
        catch (UnityException e)
        {
            Debug.LogException(e);
        }
 
        return true;
    }
}

**Comment by zhuxingwei** [comment]
这里是我们之前做可行性测试时使用的脚本，你可以参考一下实现？

**Comment by liusujin** [comment]
谢谢！这个实现和我的实现是一样的，目前使用起来未发现预期外的性能问题。
