### ISSUE TITLE
使用TextStyle绘制渐变文本的无效

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#315]
unity2018.4.8f1 windows editor dx11 uiwidgets 1.5.4preview0

`public class UIWidgetsCustomPanel : UIWidgetsPanel
    {
        protected override void OnEnable()
        {
            FontManager.instance.addFont(UnityEngine.Resources.Load<UnityEngine.Font>("MaterialIcons-Regular"), "Material Icons");
            FontManager.instance.addFont(UnityEngine.Resources.Load<UnityEngine.Font>("GalleryIcons"), "GalleryIcons");

            //UnityEngine.Font font_sans_bold = UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Font>("Assets/AddressableAssets/Font/SourceHanSansCN-Bold.otf");
            //UnityEngine.Font font_sans_regular = UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Font>("Assets/AddressableAssets/Font/SourceHanSansCN-Regular.otf");
            //FontManager.instance.addFont(font_sans_bold, "SourceHanSansCN-Bold");
            //FontManager.instance.addFont(font_sans_regular, "SourceHanSansCN-Regular");

            //AkzidenzGrotesk-LightCond

            base.OnEnable();
        }

        protected override Widget createWidget()
        {
            return new MaterialApp(
                home: new Center(
                    child: new Text("渐变文本测试",
                    style: new TextStyle(
                        fontSize: 48,
                        foreground: new Paint
                        {
                            shader = new LinearGradient(
                                begin: Alignment.topCenter,
                                end: Alignment.bottomCenter,
                                colors: new List<Color>
                                {
                                    new Color(0xFF68E194),
                                    new Color(0xFF3AC99E),
                                    new Color(0xFF56C6EE),
                                }
                                ).createShader(Rect.fromLTWH(0, 0, 300, 60))
                        }
                        )
                    )
                    )
                );
        }
    }`

**Comment by liusujin** [comment]
![image](https://user-images.githubusercontent.com/19631892/64660625-ce5c6500-d473-11e9-81cf-f0388261d90a.png)

**Comment by zhuxingwei** [comment]
hi多谢您的关注！我们这几天会看一下这个问题。多谢！

**Comment by IIzzaya** [comment]
#326 Bug已修复，已经可以支持绘制渐变文本

![image](https://user-images.githubusercontent.com/20573396/65121894-8b296580-da22-11e9-9af5-f4ea6064cda6.png)

测试代码
~~~ C#
protected override Widget createWidget() {
    return new MaterialApp(
        home: new Center(
            child: new Text("渐变文本测试",
                style: new TextStyle(
                    fontSize: 48,
                    foreground: new Paint() {
                        shader = new LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: new List<Color> {
                                new Color(0xFF68E194),
                                new Color(0xFF3AC99E),
                                new Color(0xFF56C6EE),
                            }
                        ).createShader(Rect.fromLTWH(0, 0, 300, 60))
                    }
                )
            )
        )
    );
}
~~~

- 如图显示为蓝色的文本，是因为`.createShader(Rect.fromLTWH())`的`Rect`中心不在`Center`的中心，而是在画布左上角的(0, 0)处，`Shader`是按照整个屏幕大小进行绘制，因此需自行获取到Panel的大小，将参数传入进去。
- 如有下划线，是因为没有warp一个`Scaffold`的情况下默认的`TextStyle`的`decoration`参数为`TextDecoration.underline`,需要改为`TextDecoration.none`

## 如下代码是修改后的样子

~~~ C#
protected override Widget createWidget() {
    return new MaterialApp(
        home: new Container(
            child: new Text("渐变文本测试",
                style: new TextStyle(
                    fontSize: 48,
                    foreground: new Paint() {
                        shader = new LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: new List<Color> {
                                new Color(0xFF68E194),
                                new Color(0xFF3AC99E),
                                new Color(0xFF56C6EE),
                            }
                        ).createShader(Rect.fromLTWH(0, 0, 300, 60))
                    },
                    decoration: TextDecoration.none
                )
            )
        )
    );
}
~~~
![image](https://user-images.githubusercontent.com/20573396/65122060-c166e500-da22-11e9-98cc-b4f6e57bd423.png)

## 通过包装做到自定义渐变文本

- 通过`PostFrameCallback`可以做到在每次绘制`RenderBox`后获取其`Size`和全局`Offset`，从而调整Gradient的大小和位置，让其保持在文字中央

![image](https://user-images.githubusercontent.com/20573396/65121675-38e84480-da22-11e9-84d4-b3c58f3a75ca.png)

~~~ C#
public class GradientText : StatefulWidget {
    public GradientText(Key key = null) : base(key) { }

    public override State createState() {
        return new GradientTextState();
    }
}

public class GradientTextState : State<GradientText> {
    GlobalKey myTextKey = GlobalKey.key();
    RenderBox myTextRenderBox;

    public override void initState() {
        base.initState();
        WidgetsBinding.instance.addPostFrameCallback((_) => this._recordSize());
    }

    void _recordSize() {
        this.setState(
            () => { this.myTextRenderBox = (RenderBox) this.myTextKey.currentContext.findRenderObject(); }
        );
    }

    PaintShader getTextGradient(RenderBox renderBox) {
        if (renderBox == null) return null;

        return new LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: new List<Color> {
                new Color(0xFF68E194),
                new Color(0xFF3AC99E),
                new Color(0xFF56C6EE),
            }
        ).createShader(Rect.fromLTWH(
            renderBox.localToGlobal(Offset.zero).dx,
            renderBox.localToGlobal(Offset.zero).dy,
            renderBox.size.width / Window.instance.devicePixelRatio,
            renderBox.size.height / Window.instance.devicePixelRatio)
        );
    }

    public override Widget build(BuildContext context) {
        return new Text(
            key: this.myTextKey,
            data: "渐变文本测试",
            style: new TextStyle(
                fontSize: 48,
                fontWeight: FontWeight.bold,
                foreground: new Paint() {
                    shader = this.getTextGradient(this.myTextRenderBox)
                },
                decoration: TextDecoration.none
            )
        );
    }
}
~~~
