### ISSUE TITLE
TextField使用QQ拼音或者微软拼音输入法的问题

### ISSUE THREAD

**Issue by ismyway2012** [UnityTech/UIWidgets#317]
pc平台，TextField设置了maxLength并且设置maxLengthEnforced为true，使用上述输入法输入文字接近字数上限maxLength以后，只能输入拼音字母，而不是汉字

**Comment by zhuxingwei** [comment]
hi多谢您的关注！我们这几天会看一下这个问题。多谢！

**Comment by IIzzaya** [comment]
你好，经过测试，确实会有这种问题。原因是因为`TextField`的字数识别是在达到上限后打断输入。而很多输入法的输入机制是会先将拼音填充进区域内，在选词后替换掉原本的拼音（期间还会加入空格或者逗号断词）。因此整个输入流程会在达到字数上限后被打断，造成无法输入后续汉字。

一种临时解决方案是将`maxLengthEnforced`改为`false`；另一种是自定义一个`controller`手动进行一下识别value change对输入的文字进行长度调整。

我们之后会修一下这个问题，让其behavior和UGUI的`Input Field`一致，不过优先级可能没那么高

**Comment by ismyway2012** [comment]
非常感谢！
我现在把验证输入的地方去除了compositionString后再验证就可以

**Comment by zhuxingwei** [comment]
issue fixed #327
