### ISSUE TITLE
Do you port Flutter manually?

### ISSUE THREAD

**Issue by escamoteur** [UnityTech/UIWidgets#318]
Just want to know how you port Flutter to c#? Is it done manually or were you able to build a transpiler?

**Comment by zhuxingwei** [comment]
hi. the UI framework of UIWidgets is manually ported from the Flutter framework. However, all the low layer APIs, i.e., rendering, input processing are implemented using Unity runtime SDKs.

**Comment by escamoteur** [comment]
Cool, thanks a lot. May this might be of interest for you https://github.com/adamped/xamarin.flutter

**Comment by zhuxingwei** [comment]
Yes, we have investigated this project early this year and the transpiler in xamarin.flutter sounds really great for us.
However, since this project has already been archived by the developers, we finally decide not to build UIWidgets upon it.

**Comment by escamoteur** [comment]
As far as I know Adam mainly stopped the project because he didn't want to work on it alone. I guess he might be interested again if someone would contribute.
