### ISSUE TITLE
文本框没有高亮选中文字&光标切换延迟

### ISSUE THREAD

**Issue by VDerGoW** [UnityTech/UIWidgets#32]
**系统环境**：Windows 10 64位专业版
**软件环境**：Unity 2018.3.5f1
**问题描述**：新建工程后，直接导入当前版本的UIWidgets包，在附带的测试场景（`Samples/UIWidgetSample/TextInput`）中，发现如下问题：
1. **选中高亮**：输入文本后，尝试选择文本进行编辑，选中的文本没有背景高亮，无法判断哪些文字被选中。
2. **切换延迟**：选中某个文本框之后，再选择另一个文本框，光标不能马上切换到新的文本框，会延迟大约半秒，如果这时输入内容，会把内容输入到上一个文本框。

**Comment by VDerGoW** [comment]
两个问题在编辑器和Build出来的PC可执行程序中都有发生，其他平台没有测试。

**Comment by fzhangtj** [comment]
你好，该问题已经修正.
