### ISSUE TITLE
State Management Approaches

### ISSUE THREAD

**Issue by jdnichollsc** [UnityTech/UIWidgets#320]
Hello guys,

I was wondering what state management approaches can we use with **UIWidgets**? Example: https://flutter.dev/docs/development/data-and-backend/state-mgmt/options

Exist any example with `MobX`?
Thanks in advance!

**Comment by zhuxingwei** [comment]
Hi, currently UIWidgets supports only redux as the default state management solution and you can use the build-in widget StoreProvider to access this functionality (src codes are under Runtime/redux).

We do not have any MobX examples yet but we are open for all state management solutions besides redux and will introduce them to UIWidgets whenever we have time. Thanks !

**Comment by jdnichollsc** [comment]
Awesome, thanks!
