### ISSUE TITLE
EditableText这个控件目前会报错  

### ISSUE THREAD

**Issue by coolengine** [UnityTech/UIWidgets#329]
![image](https://user-images.githubusercontent.com/16344619/65860351-b013c600-e39c-11e9-85a8-d8f3493dfca7.png)
EditableText这个控件目前会报错

**Comment by zhuxingwei** [comment]
你需要把这个Widget放到一个WidgetsApp或者MaterialApp下面。具体请参考出错信息中的提示。建议您可以从我们给的Sample出发来尝试学习和使用UIWidgets
