### ISSUE TITLE
请问UIWidgets有没有类似flutter_swiper这样的轮换图代码

### ISSUE THREAD

**Issue by coolengine** [UnityTech/UIWidgets#335]
https://github.com/best-flutter/flutter_swiper
就是类似这样的，因为app开发避免不了要是用轮播的效果，我看了官方提供的demo里没有这样的组件  还是我没找到？是不是没有啊？

**Comment by zhuxingwei** [comment]
嗯嗯，由于我们人手有限，目前主要工作还是维护以及优化现有的框架，暂时还没有做类似的高级组件的计划。如果您急需要使用的话可以考虑先自行写一版？

**Comment by coolengine** [comment]
好的 我根据flutter_swiper自己先写一般  感谢大佬回复

**Comment by zhuxingwei** [comment]
嗯嗯，你这边遇到任何问题随时在这个issue下面随时交流。等搞定以后欢迎将你的repo share给我们，我们可以放到我们的plugin列表里面。多谢！

**Comment by coolengine** [comment]
好的好的，我学习了一段时间的UIWidgets  辛苦像你们这样的团队了，把这么好的框架搬到unity上来，因为我本身就一直在用unity，期待UIWidgets越来越丰富，越来越强大，辛苦大佬们，感谢你们的付出

**Comment by yczhangsjtu** [comment]
Connect App的代码里shopping_mall_detail分支里已经把flutter_swiper搬了过来。

https://github.com/UnityTech/ConnectAppCN/tree/shopping_mall_detail/Assets/ConnectApp/Components/Swiper

**Comment by coolengine** [comment]
卧巢,感谢大佬提点 感谢！！！！！！！十分感谢
