### ISSUE TITLE
cannot find font error after updating to the latest dev branch

### ISSUE THREAD

**Issue by zhuxingwei** [UnityTech/UIWidgets#353]
![image](https://user-images.githubusercontent.com/4134652/67183362-d533ab80-f413-11e9-8de0-f11222f907ab.png)

are the font files missing ?

**Comment by yczhangsjtu** [comment]
The font files have recently been moved to `Runtime/Resources/fonts/' folder. Please prepend the font file names in your code by `fonts/`, for example:

```
FontManager.instance.addFont(Resources.Load<Font>(path: "fonts/MaterialIcons-Regular"), "Material Icons");
```
