### ISSUE TITLE
建议统一命名风格

### ISSUE THREAD

**Issue by VDerGoW** [UnityTech/UIWidgets#36]
目前UIWidgets框架中**文件夹名、文件名、命名空间名、类方法名**中均出现了**命名风格不统一**的情况，同类型对象有些是全小写命名，有些是单词首字母大写命名，有些是全大写命名。

**建议趁目前框架还没有大范围推广，统一框架的命名风格。**

既然作为Unity的扩展，而且使用C#语言，那么命名风格应该**遵守Unity和C#的约定**。这一框架的灵感来自Flutter，但不应该全部照着Flutter来，应该重点还原其编程思想，而不是命名风格。

**Comment by kgdev** [comment]
嗯嗯 我们一开始想过这个问题，结论是觉得c#对于unity来说就是个脚本语言，不用follow .net的风格。
为了方便，沿用js/dart的小写打头风格。
