### ISSUE TITLE
怎么适配异形屏幕？如刘海屏， SafeArea 中的padding值一直为0

### ISSUE THREAD

**Issue by BrickCar** [UnityTech/UIWidgets#392]

**Comment by BrickCar** [comment]
原生flutter 取值正常，华为 EMUI8.2.0

**Comment by zhuxingwei** [comment]
多谢反馈！请问一下您这边SafeArea的padding值是怎么得到的？具体是哪一个variable？是否可以截屏说明一下具体问题？

其次，麻烦你确认一下：（1）你的App是全屏模式还是使用了非全屏插件（显示状态栏）？（2）你所使用的Unity版本？（3）你项目的manifest里是否enable了android_notch_support？

最后，根据我们这边对类似Android机型的测试，如果你的App需要显示状态栏，那么通过使用对应的aar插件以及勾选render outside of safe area就可以实现正常显示；反之，则关闭render outside of safe area选项后也是正确的。你可以借鉴一下
