### ISSUE TITLE
使用TextField报错

### ISSUE THREAD

**Issue by songcy950605** [UnityTech/UIWidgets#395]
新建了一个TextField 只要点击输入框就会报错
```
public class UIChatScreen : StatefulWidget
{
    public override State createState()
    {
        return new ChatScreen();
    }
}

public class ChatScreen : State<StatefulWidget>
{

    TextEditingController controller = new TextEditingController();
    FocusNode _focusNode = new FocusNode();
    public override void initState()
    {
        base.initState();

        _focusNode.addListener(focusListener);
    }

    void focusListener()
    {
        UnityEngine.Debug.LogError(_focusNode.hasFocus);
    }

    public override Widget build(BuildContext context)
    {
        return new Container(
            width: 550f,
            height:50,
            alignment:Alignment.center,
            child: new TextField(
                focusNode: _focusNode,
                style: new TextStyle(
                    color: Color.fromARGB(255, 255, 238, 204),
                    fontSize: 20,
                    decoration: TextDecoration.none,
                    fontWeight: FontWeight.normal
                    ),
                controller: controller
                )
            );
    }
}
```
![image](https://user-images.githubusercontent.com/58412936/69933191-cbb85b80-1508-11ea-8ecc-008cf9b9da0d.png)

**Comment by yczhangsjtu** [comment]
UIChatScreen继承的是State，不是State<UIChatScreen>？

**Comment by yczhangsjtu** [comment]
`ChatScreen`改为继承`State<UIChatScreen>`试一下看？

**Comment by songcy950605** [comment]
> `ChatScreen`转变继承`State<UIChatScreen>`试一下看？

不行，还是会有

**Comment by yczhangsjtu** [comment]
我这边用你的例子运行了一下，一切正常，没有报错。能否给一个最小的可以复现这个错误的完整样例？

**Comment by songcy950605** [comment]
> 我这边用你的例子运行了一下，一切正常，没有报错。能否给一个最小的可以复现这个错误的完整样例？

外部就是一个panel  添加的脚本为
·`using Unity.UIWidgets.ui;
using Unity.UIWidgets.widgets;
using UnityEngine;

public class UIChatPanel : UIWidgetsPanel
{
    public static UIChatPanel instance;

    public UIChatPanel()
    {
        instance = this;
    }

    protected override void OnEnable()
    {
        base.OnEnable();
    }

    protected override Widget createWidget()
    {
        return new MaterialApp(
            home: new UIChatScreen()
        );
    }
   
}`
就没其他的了

**Comment by yczhangsjtu** [comment]
在`MaterialApp`中套一层`Material`试一下？

就像这样
```
new MaterialApp(
  home: new Material(
    child: new UIChatScreen()
  )
)
```

**Comment by songcy950605** [comment]
> 在`MaterialApp`中套一层`Material`试一下？
> 
> 就像这样
> 
> ```
> new MaterialApp(
>   home: new Material(
>     child: new UIChatScreen()
>   )
> )
> ```

可以了  谢谢
