### ISSUE TITLE
有没有国际化的sample

### ISSUE THREAD

**Issue by cracker999999** [UnityTech/UIWidgets#397]
可以跟随系统语言 并可在app内切换语言

**Comment by zhuxingwei** [comment]
多谢关注！localization在UIWidgets中是直接支持的。由于时间原因，对应的Sample我们暂时还没有，不过您可以参考flutter的样例。十分抱歉！

**Comment by zhuxingwei** [comment]
using System.Collections.Generic;
using RSG;
using Unity.UIWidgets.engine;
using Unity.UIWidgets.material;
using Unity.UIWidgets.rendering;
using Unity.UIWidgets.service;
using Unity.UIWidgets.ui;
using Unity.UIWidgets.widgets;
using UnityEngine;

namespace DefaultNamespace
{
    public class DemoLocalization
    {
        private readonly Locale locale;

        public DemoLocalization(Locale locale)
        {
            this.locale = locale;
        }
        
        static readonly Dictionary<string, Dictionary<string, string>> _localizedValues = new Dictionary<string, Dictionary<string, string>>
        {
            {"en", new Dictionary<string, string>
            {
                {"task title", "flutter demo"}
            }},
            {"zh", new Dictionary<string, string>
            {
                {"task title", "flutter 例子"}
            }}
        };

        public string title => _localizedValues[locale.languageCode]["task title"];
        
        public static DemoLocalization of(BuildContext context){
            return Localizations.of<DemoLocalization>(context, typeof(DemoLocalization));
        }
    }

    public class DemoLocalizationsDelegate : LocalizationsDelegate<DemoLocalization>
    {
        public override bool isSupported(Locale locale)
        {
            return locale.languageCode == "en" || locale.languageCode == "zh";
        }

        public override IPromise<object> load(Locale locale)
        {
            return Promise<object>.Resolved(new DemoLocalization(locale));
        }

        public override bool shouldReload(LocalizationsDelegate old)
        {
            return false;
        }
        
        public static readonly DemoLocalizationsDelegate DemoDelegate = new DemoLocalizationsDelegate();
    }


    public class DefaultMaterialLocalizationsCN : DefaultMaterialLocalizations
    {
        public static readonly _MaterialLocalizationsDelegateCN DemoDelegate = new _MaterialLocalizationsDelegateCN();
    }


    public class _MaterialLocalizationsDelegateCN : LocalizationsDelegate<MaterialLocalizations> {
        public _MaterialLocalizationsDelegateCN() {
        }

        public override bool isSupported(Locale locale) {
            return locale.languageCode == "en" || locale.languageCode == "zh";
        }

        public override IPromise<object> load(Locale locale) {
            return DefaultMaterialLocalizations.load(locale);
        }

        public override bool shouldReload(LocalizationsDelegate old) {
            return false;
        }

        public override string ToString() {
            return "DefaultMaterialLocalizations.delegate(en_US)";
        }
    }
    
    public class DemoLocalizations : UIWidgetsPanel
    {
        protected override void OnEnable()
        {
            FontManager.instance.addFont(Resources.Load<Font>("fonts/MaterialIcons-Regular"), "Material Icons");
            base.OnEnable();
        }

        protected override Widget createWidget()
        {
            return new MyApp2();
        }
    }

    public class MyApp3 : StatelessWidget
    {
        public override Widget build(BuildContext context)
        {
            return new Scaffold(
                    appBar: new AppBar(title: new Text("Title")),
                    body: new Column(
                        children: new List<Widget>{
                            new Text(DemoLocalization.of(context).title),
                            new ConstrainedBox(
                                constraints: new BoxConstraints(
                                    maxHeight: 120.0f
                                ),
                                child: new TextField(
                                    maxLines: 4,
                                    minLines: 1,
                                    maxLengthEnforced: false,
                                    keyboardType: TextInputType.multiline
                                )
                            ),
                            new Container(height: 20.0f,width: 200.0f,color: Colors.red)
                        }
                    )
                );
        }
    }

    public class MyApp2 : StatelessWidget
    {
        public override Widget build(BuildContext context)
        {
            return new MaterialApp(
                title: "flutter demo",
                home: new MyApp3(),
                localizationsDelegates: new List<LocalizationsDelegate>
                {
                    DefaultMaterialLocalizationsCN.DemoDelegate,
                    DemoLocalizationsDelegate.DemoDelegate,
                },
                locale: new Locale("zh", "CN"), // this is for Chinese, set as new Locale("en", "US") for English
                supportedLocales: new List<Locale>
                {
                    new Locale("zh", "CN"),
                    new Locale("en", "US")
                }
            );
        }
    }
}

**Comment by zhuxingwei** [comment]
请参考以上示例
