### ISSUE TITLE
请问这个项目还在正常推进么？

### ISSUE THREAD

**Issue by ChrisPei** [UnityTech/UIWidgets#403]
貌似主分支2个月没动静了。

**Comment by Leacae** [comment]
顶起来，不要让我们失望啊

**Comment by zhuxingwei** [comment]
目前我们还在推进中。主要人员目前在开发ConnectApp项目所需的新feature。等版本稳定后我们再选择合适的feature移植回UIWidgets

**Comment by ChrisPei** [comment]
> 目前我们还在推进中。主要人员目前在开发ConnectApp项目所需的新feature。等版本稳定后我们再选择合适的feature移植回UIWidgets

那就太好了~
