### ISSUE TITLE
建议在README中增加关于设置图标字体的说明

### ISSUE THREAD

**Issue by lunoctis** [UnityTech/UIWidgets#404]
现在的说明是在OnEnable()中的注释......不注意就漏过去了
新建项目后很奇怪为什么图标不显示, 检查一遍后才发现没添加图标字体, 然后去下载了一个Material Icon字体加载进去正常了...
感觉加个醒目点的说明更好些

**Comment by Leacae** [comment]
protected override void OnEnable() {
             // if you want to use your own font or font icons.
             // FontManager.instance.addFont(Resources.Load<Font>(path: "path to your font"), "font family name");

             // add material icons, familyName must be "Material Icons"
             // FontManager.instance.addFont(Resources.Load<Font>(path: "path to material icons"), "Material Icons");

             base.OnEnable();
         }

**Comment by Leacae** [comment]
public class UIWidgetsExample : UIWidgetsPanel {
         protected override void OnEnable() {
             // if you want to use your own font or font icons.
             // FontManager.instance.addFont(Resources.Load<Font>(path: "path to your font"), "font family name");

             // load custom font with weight & style. The font weight & style corresponds to fontWeight, fontStyle of
             // a TextStyle object
             // FontManager.instance.addFont(Resources.Load<Font>(path: "path to your font"), "Roboto", FontWeight.w500,
             //    FontStyle.italic);

             // add material icons, familyName must be "Material Icons"
             // FontManager.instance.addFont(Resources.Load<Font>(path: "path to material icons"), "Material Icons");

             base.OnEnable();
         }

**Comment by Leacae** [comment]
是你自己没看到！

**Comment by lunoctis** [comment]
> 
> 
> 是你自己没看到！

对, 没看到, 我眼瞎
说的就是能不能醒目一点单拉在README一个标题出来
你要是说这个项目就是面向精英的不适合星际选手那我无话可说

**Comment by Leacae** [comment]
任何东西都要自己摸索的，不可能UIWidgets任何东西都列的明明白白，如果有什么问题以后可以参考flutter

**Comment by zhuxingwei** [comment]
这个我们会考虑一下是否添加进readme。不过，针对这个特定问题，我们更倾向于放到wiki里。UIWidgets wiki的制作我们目前还在计划中，我们会将这个问题放入到check list里。多谢两位的关注！
