### ISSUE TITLE
UIWidgets 性能问题

### ISSUE THREAD

**Issue by carefree0910** [UnityTech/UIWidgets#406]
TL; DR：**当前的 UIWidgets 代码仓库是否存在性能问题？如果是的话，未来大概什么时候会优化？**

最近尝试学习 UIWidgets，发现自己写的示例 app 即使非常简单，也会有非常肉眼可见的性能问题，比如说：
1）用 PageView 切换页面时很卡
2）Switch Widgets 的动画很卡

用 graphy 看了看，确实在上述两种场景下 fps 会掉得特别厉害
由于在 Editor 上能流畅运行，一开始觉得是自己测试机性能太差，但【**ConnectApp**】是能流畅运行的，所以怀疑是实现的问题
上网查了查，用上了一些常用的小优化，问题没有得到解决
后面把官方的【**Gallery**】打包下来试了试，发现【**性能问题更加严重**】，所以又怀疑是这边的 UIWidgets 并不是最新版、又或是直接用 unity 打包本身会存在性能问题
看了看 issue，有提到动态 fps，有提到未来会把 ConnectApp 那边的功能迁移过来，所以我这边也不好判断到底是我写拐了还是说当前的 UIWidgets 尚未成熟
所以就回到抬头的问题了：**当前的 UIWidgets 代码仓库是否存在性能问题？如果是的话，未来大概什么时候会优化？**

**Comment by zhuxingwei** [comment]
多谢反馈！目前UIWidgets的性能问题我们都是有跟踪的，并没有已知的显著问题。此外ConnectApp应该是没有额外的优化功能的。你可以先看看是否是动态调节FPS的机制造成的卡顿？另外，你还可以看看是否是打开了UIWidgets_DEBUG？

**Comment by carefree0910** [comment]
您好，多谢回复！受到您的启发，我发现是我忘了去除 Development Build 勾选项，导致了一部分的性能问题
不过在改掉这个问题之后，虽然我写的那个简单的示例 app 【**稍有**】改善，但是【**Gallery**】在我手机（【**红米 Note 8**】）上的性能问题**仍然非常严重**，反观【**ConnectApp**】则相当流畅，不知这是否正常？

**Comment by zhuxingwei** [comment]
这个情况并不正常。ConnectApp的UI复杂程度应该是比Gallery高的。应该还是Build配置的问题。目前为了方便初学者的学习使用，因此Gallery Sample开启了动态FPS调节等可能影响性能的feature。这个可能是你所遇到的性能问题的原因。

如果方便的话你能大概描述一下你遇到的性能问题吗？例如贴一下对应的profiler数据？多谢！

**Comment by carefree0910** [comment]
您好，由于我是初学者，只能从网上查阅到的资料来尝试做 profile，不知道是否符合您的需求；这是我的 setup 步骤：
1. 新建 Unity 3D 项目（版本：2019.2.18f1）
2. 从 Asset Store 中 import UIWidgets
3. 用 unity [官方文档中介绍的内置 profiler](https://docs.unity3d.com/2019.2/Documentation/Manual/iphone-InternalProfiler.html) 进行了 profile。为此，我不得不开启了 Enable Internal Profiler (Deprecated) 与 Development Build 
4. 在我的测试机 红米 Note 8 上，点击主页右上方的 drawer

结果如下：

![image](https://user-images.githubusercontent.com/15677328/74000201-328f4080-49a2-11ea-9e7f-c73b4a1ceb53.png)

我注意到这里面有一项 WaitForTargetFPS，占据了大部分开销，不知是否就是动态 fps 带来的问题？

**Comment by zhuxingwei** [comment]
hi，多谢反馈！从你的图中看到问题应该出在VSync上。这个在UIWidgets项目中我们是默认要关掉的。你可参考https://blog.csdn.net/Xushuai0616/article/details/56275771 关掉再试试？

**Comment by carefree0910** [comment]
感谢回复！我之前发现是 VSync 占了很大开销时，特地上网查了查能否关掉，发现一般的 Unity 项目不能将其关闭，所以就没有细究，漏掉了 UIWidgets 对此有特殊处理的可能性

不过，在参考链接、设置为 Don't Sync 之后，虽然性能有了一些改善，但还是不尽人意。经过 profile，发现了一些问题（行为仍然是点击主页右上方的 drawer）：

+ Vsync 看上去仍然存在（见下面的几张图）
+ 有一帧的性能特别差（这是第 51 帧）

![image](https://user-images.githubusercontent.com/15677328/74096775-2b049e80-4b3e-11ea-8888-c10dc007cf21.png)

+ WaitForTargetFPS 仍然存在（这些是第 52 - 54 帧）

![image](https://user-images.githubusercontent.com/15677328/74096803-77e87500-4b3e-11ea-9636-878c67cecab2.png)
![image](https://user-images.githubusercontent.com/15677328/74096805-7c149280-4b3e-11ea-880b-11c43ada0614.png)
![image](https://user-images.githubusercontent.com/15677328/74096807-7f0f8300-4b3e-11ea-95cf-70f1be3bedf2.png)

不知我是否还是有哪里没有设置对？

**Comment by zhuxingwei** [comment]
嗯嗯，这一帧的卡顿主要是Mono.JIT相关的操作引起的。这个是Mono在动态的Compile C#，只会在函数第一次调用时执行。之后应该就不会有这个卡顿了。你可以试试切换到il2cpp的script backend，应该可以消除这个问题。

**Comment by carefree0910** [comment]
您好，由于我最终项目出于未知原因（我个人估计是因为 prefab 太多），导致 il2cpp 的 build 时长特别长（事实上我没成功 build 过，因为等过一个小时都没 build 出来），所以智能用 mono

那么，除了这一帧卡顿以外，后面三张图对应的 3 帧的表现是否正常？因为体感 Gallery 的性能仍然相当差，动画播出来都是一卡一卡的，而 ConnectApp 就没这个问题。理论上如果只是 mono 这个问题，那么后续应该会比较流畅才对

**Comment by zhuxingwei** [comment]
嗯嗯，多谢反馈！抱歉回复的晚了一点。图上的结果看起来仍然不是正常的。时间消耗上看大部分事件都是在等待。我这边可能需要花点时间在我本地复现一下你的这个结果。

**Comment by carefree0910** [comment]
嗯嗯好的，多谢帮助！

我这边的复现步骤如下：
1. 新建 Unity 3D 项目（版本：2019.2.18f1）
2. 从【**Asset Store**】中 import UIWidgets（会不会是因为 Asset Store 上的不是最新版本？）
3. 打开 gallery Scene，build 时勾选上 Development Build（为了 profile）

**Comment by zhuxingwei** [comment]
哦哦，Asset Store里面的版本已经很老了。建议直接用GitHub拉最新的代码和测试Sample（具体Repo参见README）

**Comment by carefree0910** [comment]
原来如此，我之所以用 Asset Store 是因为比较方便，同时也因为之前尝试过使用 GitHub 版本，但总是有一些小问题

不知您是否有更新 Asset Store 版本的打算？如果没有的话，我尝试一下迁移至 GitHub 的 master；如果有的话，可能等一下 Asset Store 最新版本对我而言是最无痛的（因为现在已经在上面写了挺久了哈哈哈）

**Comment by zhuxingwei** [comment]
暂时还没有更新Asset Store版本的计划。比较建议您直接使用GitHub拉代码，这样可以比较方便的获得我们最新的修改

**Comment by carefree0910** [comment]
明白了，非常感谢您的耐心回复！

**Comment by carefree0910** [comment]
您好，我在删除 Asset Store 的版本并按照 README 将 GitHub 的 master 版本放在 Packages 中后，报了如下错误：

NullReferenceException: Object reference not set to an instance of an object
Unity.UIWidgets.ui.FontManager.addFont (UnityEngine.Font font, System.String familyName, Unity.UIWidgets.ui.FontWeight fontWeight, Unity.UIWidgets.ui.FontStyle fontStyle) (at Packages/com.unity.uiwidgets/Runtime/ui/painting/txt/font_manager.cs:42)
App.App.OnEnable () (at Assets/App/App.cs:480)

我用的版本是 2019.2.18f1，不知这个是版本兼容问题还是？

**Comment by zhuxingwei** [comment]
我们对目录结构做了调整，目前的 Fonts 文件的路径在Fonts目录下。具体可参考：FontManager.instance.addFont(Resources.Load<Font>("fonts/MaterialIcons-Regular"), "Material Icons");

**Comment by carefree0910** [comment]
明白了，非常感谢您的指导！
