### ISSUE TITLE
How to make bottomNavigationBar with router ? 

### ISSUE THREAD

**Issue by bombiGo** [UnityTech/UIWidgets#407]
help me, my english is not good. I want to add navigation route in bottomNavigationBar.

dart language: 
onGenerateRoute: (RouteSettings settings) {
        return MaterialPageRoute(
          settings: settings,
          builder: (BuildContext context) {
            switch(settings.name) {
              case '/':
                return RootPage(destination: widget.destination);
              case '/list':
                return ListPage(destination: widget.destination);
              case '/text':
                return TextPage(destination: widget.destination);
            }
          },
        );

but how to generate onGenerate() ? I not showing this function! help me, thanks

**Comment by zhuxingwei** [comment]
ConnectApp项目应该有类似的功能，你可以到参考一下该项目的代码？

**Comment by bombiGo** [comment]
thanks
