### ISSUE TITLE
UIWidgets 显示问题

### ISSUE THREAD

**Issue by carefree0910** [UnityTech/UIWidgets#408]
在我将项目中的【**Asset Store**】版本的 UIWidgets，换成【**master branch**】 的版本并导入到 Packages 中后，发现在手机屏幕抬头处有较为明显的显示问题（【之前是不存在的】），且不同机型的这个显示问题表现还不一样：

+ 红米 Note 8：
![Screenshot_2020-02-12-19-12-37-081_com AIIC App](https://user-images.githubusercontent.com/15677328/74330068-f574e500-4dcb-11ea-9e80-ea4d2319bd62.jpg)
可以看到，抬头处有一些蓝色的颜色块

+ 小米 Mix 2：
![Screenshot_2020-02-12-19-16-38-359_com AIIC App](https://user-images.githubusercontent.com/15677328/74330396-9499dc80-4dcc-11ea-82c8-916545540915.jpg)
可以看到，抬头处有一些下面 UI 的影子；此外在程序运行过程中，抬头处会出现闪屏的现象

不知这是属于我的编码问题，还是属于兼容性问题？

**Comment by zhuxingwei** [comment]
是否能share一下你的测试代码？是你这边所有机器上有这类问题还是只有上述例子中的两个机型会有问题？我们这边master branch每次更新后都有QA在做机型回归测试，不应该有这种问题。

**Comment by carefree0910** [comment]
测试代码比较难抽出来，以及我手头上只有这两个机型，但都出现了问题。
时间原因，我暂时只能尽可能描述一下我的 unity 配置，看看会不会有帮助：
+ Unity 版本：2019.3.3f1
+ 用了 Development Build
+ 用了 IL2CPP

**Comment by zhuxingwei** [comment]
多谢您的反馈！方便的话请您使用2019.1.14f1这个版本的Unity。我们目前暂时还没有完整的对后面版本Unity进行测试和修复，因此可能会存在问题。其他两个配置应该还好。麻烦了！

**Comment by carefree0910** [comment]
明白了，感谢您的帮助！
