### ISSUE TITLE
Setting the correct format for C#.

### ISSUE THREAD

**Issue by gaegaelab** [UnityTech/UIWidgets#414]
Writing function arguments on multiple lines in C# is not formatted properly.
The position of blanks and brackets is incorrect.
I have tried VisualStudio2017 and VSCode, but both have incorrect formats.
Is there a good formatter?
Or if you have the correct format settings, please let me know.

**Comment by zhuxingwei** [comment]
Hi, we apply the code style format as described in https://github.com/UnityTech/UIWidgets/blob/master/CONTRIBUTING.md 
in UIWidgets.

**Comment by gaegaelab** [comment]
Thank you for your response.
 I will consider purchasing Rider.😅
