### ISSUE TITLE
关于异步AssertionError: Window.instance is null

### ISSUE THREAD

**Issue by Linspirit98** [UnityTech/UIWidgets#415]
我在readme中看到了这个error的解决方案，但是由于我在我的工程中使用了路由，因此http异步中的解决方案好像不太适合我。我没有办法在对应的body里面传参。请问如何能够在使用路由的情况下完成这个功能呢。

![image](https://user-images.githubusercontent.com/51519489/76686951-00eb4400-65f6-11ea-87b5-1bba228969ea.png)

**Comment by zhuxingwei** [comment]
多谢你的反馈！这种类型需求的最佳实践您可以直接在我们的ConnectApp源码中看到。建议你移步看一下？https://github.com/UnityTech/ConnectAppCN

**Comment by Linspirit98** [comment]
谢谢您，问题解决了！
