### ISSUE TITLE
Question about DropdownButton 

### ISSUE THREAD

**Issue by Linspirit98** [UnityTech/UIWidgets#416]
Hi, 

I am trying to put the country code of phone numbers into a dropdown box using dropdown button.  I read the country code from json file with keys and values. 

However, UI widgets doesn't have map function. I cound't find any sample the address this issue. Are there any solutions?

**Comment by zhuxingwei** [comment]
Maybe this can help? https://stackoverflow.com/questions/2142935/what-is-the-c-sharp-equivalent-of-map-function-in-haskell
Feel free to let me know if this doesn't work as you wished

**Comment by Linspirit98** [comment]
Thank you for your reply! This issue has been solved! The solution was found in date_and_time_picker_demo.cs.
