### ISSUE TITLE
如何实现已渲染的页面内容，获取数据后得到更新？

### ISSUE THREAD

**Issue by gier0759** [UnityTech/UIWidgets#422]
通过接口更新的变量值，并没有使已渲染的内容发生改变。（渲染的页继承自StatelessWidget；接口在进入页面时立即调用）
更新的内容是用户名、邮箱等必须从后台获取的信息。
期望的状态：页面相应位置从空白更新成带用户信息的状态

**Comment by Leacae** [comment]
你好 ，StatelessWidget 组件是无状态的（就是无法更新数据），如果你需要更新页面的数据，就需要用StatefulWidget组件，并且需要一个维护自身状态的State类！相关案例可以参考Flutter
