### ISSUE TITLE
请问UIWidgets支持用热更新么？比如说用lua来写UI

### ISSUE THREAD

**Issue by pengjipan** [UnityTech/UIWidgets#423]

**Comment by Leacae** [comment]
官方表示UIWidgets目前不支持Lua热更新！

**Comment by pengjipan** [comment]
> 官方表示UIWidgets目前不支持Lua热更新！

额，那有没有什么热更新方案？

**Comment by Leacae** [comment]
目前UIWidgets官方表示不支持热更新的

**Comment by zhuxingwei** [comment]
多谢您的关注！基于IOS上对于热更新的敏感性以及涉及到的工作量方面的考虑，我们短期内不会考虑支持基于Lua等脚本语言的热更机制。
