### ISSUE TITLE
add Spacer class for Flex containers

### ISSUE THREAD

**Issue by TsubasaK111** [UnityTech/UIWidgets#424]
Hi there! First issue here, huge fan of this library.

I noticed that the [Spacer class](https://api.flutter.dev/flutter/widgets/Spacer-class.html) is missing from this library. Is there a particular reason?

It seems that would be a relatively simple implementation and the topic has [already been brought up previously](https://github.com/UnityTech/UIWidgets/issues/190).

**Comment by zhuxingwei** [comment]
Thanks for the report ! We have added the Spacer class in our Dev branch, please try it out and ping us if you have any new question.
