### ISSUE TITLE
flat button 长按 这个波纹能和 装饰盒一样

### ISSUE THREAD

**Issue by weacw** [UnityTech/UIWidgets#43]
![image](https://user-images.githubusercontent.com/11573490/53719383-d8842200-3e98-11e9-8afe-399829e0dd68.png)

望flat button 长按时这个波纹能和装饰盒一样 而不是长方形的

**Comment by zhuxingwei** [comment]
麻烦确认一下你那边是这行实现Button Shape的吗？我用这种实现方式时波纹会被正确的裁剪，并不是长方形的。return new Material(
                child: new Center(
                    child: new FlatButton(
                        shape: new RoundedRectangleBorder(borderRadius: BorderRadius.all(20.0f)),
                        color: new Color(0xFF00FF00),
                        splashColor: new Color(0xFFFF0011),
                        highlightColor: new Color(0x88FF0011),
                            child: new Text("Click Me"),
                        onPressed: () => { Debug.Log("pressed here"); }
                    )
                )
            );
如果你不是这样实现的话，麻烦贴一下实现代码，我再试一试，多谢
