### ISSUE TITLE
Is this project going to have continued support from unity? 

### ISSUE THREAD

**Issue by ArEnSc** [UnityTech/UIWidgets#457]
I want to understand if I should use this project, I am thinking that it might be dead and risky to use, though it seems stable.

**Comment by MobilEKG** [comment]
It looks like they are working on new version here. I do see active development activities here. Hopefully, they will release the new build soon.
https://github.com/Unity-Technologies/com.unity.uiwidgets/issues/10

**Comment by ArEnSc** [comment]
@MobilEKG Amazing! thats awesome! this package is sooo goood omg its what unity is missing

**Comment by ArEnSc** [comment]
Closed yeah they are working on a new build soon
