### ISSUE TITLE
使用UIWidgets开发游戏UI的性能问题

### ISSUE THREAD

**Issue by RF103T** [UnityTech/UIWidgets#460]
按照指南在现有游戏项目中加入示例时，游戏运行会变得非常卡顿。所以我不得不用以下代码来避免游戏卡顿：
`Window.onFrameRateSpeedUp = () => { };`
`Window.onFrameRateCoolDown = () => { };`
但是我不知道这样会不会产生其他影响，所以想问一下这是在游戏项目中使用UIWidgets必须设置的步骤吗？还是我有什么地方没有注意到而导致了这种卡顿？

**Comment by kuro7766** [comment]
我的理解是这个库主要做手机app的，默认降低频率是减少功耗用的
3d界面变卡必须自己设置频率

**Comment by kuro7766** [comment]
我一般这么用的

```csharp
//任意位置加入
void OnUpdate(){
  OnDemandRendering.renderFrameInterval = 1;
}
```

**Comment by RF103T** [comment]
@kuro7766 谢谢！
