### ISSUE TITLE
图文混排，图片较多时报错：RenderTexture.Create failed: requested size is too large.

### ISSUE THREAD

**Issue by luoxuguang** [UnityTech/UIWidgets#48]
RenderTexture.Create failed: requested size is too large.
UnityEngine.Graphics:ExecuteCommandBuffer()
Unity.UIWidgets.ui.PictureFlusher:flush(Picture) (at Packages/com.unity.uiwidgets/Runtime/ui/painting/canvas_impl.cs:758)
Unity.UIWidgets.ui.CommandBufferCanvas:flush() (at Packages/com.unity.uiwidgets/Runtime/ui/painting/canvas_impl.cs:1014)
Unity.UIWidgets.flow.RasterCache:_rasterizePicture(Picture, Matrix3, Single, MeshPool) (at Packages/com.unity.uiwidgets/Runtime/flow/raster_cache.cs:232)
Unity.UIWidgets.flow.RasterCache:getPrerolledImage(Picture, Matrix3, Single, Boolean, Boolean) (at Packages/com.unity.uiwidgets/Runtime/flow/raster_cache.cs:169)
Unity.UIWidgets.flow.PictureLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/picture_layer.cs:39)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.ClipRectLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/clip_rect_layer.cs:19)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.ClipRectLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/clip_rect_layer.cs:19)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.ContainerLayer:prerollChildren(PrerollContext, Matrix3, Rect&) (at Packages/com.unity.uiwidgets/Runtime/flow/container_layer.cs:26)
Unity.UIWidgets.flow.TransformLayer:preroll(PrerollContext, Matrix3) (at Packages/com.unity.uiwidgets/Runtime/flow/transform_layer.cs:25)
Unity.UIWidgets.flow.LayerTree:preroll(ScopedFrame, Boolean) (at Packages/com.unity.uiwidgets/Runtime/flow/layer_tree.cs:35)
Unity.UIWidgets.flow.ScopedFrame:raster(LayerTree, Boolean) (at Packages/com.unity.uiwidgets/Runtime/flow/compositor_context.cs:27)
Unity.UIWidgets.editor.Rasterizer:_drawToSurface(LayerTree) (at Packages/com.unity.uiwidgets/Runtime/editor/rasterizer.cs:72)
Unity.UIWidgets.editor.Rasterizer:_doDraw(LayerTree) (at Packages/com.unity.uiwidgets/Runtime/editor/rasterizer.cs:56)
Unity.UIWidgets.editor.Rasterizer:draw(LayerTree) (at Packages/com.unity.uiwidgets/Runtime/editor/rasterizer.cs:40)
Unity.UIWidgets.editor.WindowAdapter:render(Scene) (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:397)
Unity.UIWidgets.rendering.RenderView:compositeFrame() (at Packages/com.unity.uiwidgets/Runtime/rendering/view.cs:121)
Unity.UIWidgets.rendering.RendererBinding:drawFrame() (at Packages/com.unity.uiwidgets/Runtime/rendering/binding.cs:69)
Unity.UIWidgets.widgets.WidgetsBinding:drawFrame() (at Packages/com.unity.uiwidgets/Runtime/widgets/binding.cs:124)
Unity.UIWidgets.rendering.RendererBinding:_handlePersistentFrameCallback(TimeSpan) (at Packages/com.unity.uiwidgets/Runtime/rendering/binding.cs:61)
Unity.UIWidgets.scheduler.SchedulerBinding:_invokeFrameCallback(FrameCallback, TimeSpan, StackTrace) (at Packages/com.unity.uiwidgets/Runtime/scheduler/binding.cs:357)
Unity.UIWidgets.scheduler.SchedulerBinding:handleDrawFrame() (at Packages/com.unity.uiwidgets/Runtime/scheduler/binding.cs:298)
Unity.UIWidgets.scheduler.SchedulerBinding:_handleDrawFrame() (at Packages/com.unity.uiwidgets/Runtime/scheduler/binding.cs:235)
Unity.UIWidgets.editor.WindowAdapter:_beginFrame() (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:264)
Unity.UIWidgets.editor.WindowAdapter:_doOnGUI(Event) (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:272)
Unity.UIWidgets.editor.WindowAdapter:OnGUI(Event) (at Packages/com.unity.uiwidgets/Runtime/editor/editor_window.cs:240)
Unity.UIWidgets.engine.UIWidgetWindowAdapter:OnGUI(Event) (at Packages/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs:56)
Unity.UIWidgets.engine.UIWidgetsPanel:Update() (at Packages/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs:172)

**Comment by kgdev** [comment]
Please try to use ListView.builder. It should be able to fix this problem.
