### ISSUE TITLE
support xamarin is a must

### ISSUE THREAD

**Issue by juepiezhongren** [UnityTech/UIWidgets#54]
native api for non-ui things r in strong request.

**Comment by liusujin** [comment]
i agree with you.

**Comment by kgdev** [comment]
Could you please elaborate a bit more on this?

What's the "native api" you mean?

**Comment by juepiezhongren** [comment]
@kgdev xamarin.ios and xamarin.android map all the oc and java apis to C#, and even create some common lib like xamarin.essentials which do things like shake, camera etc... 
u3d is great things for game and uni-rendering app, and native apis with C# language could boost all together into a much higher level for devs.

**Comment by kgdev** [comment]
yes, agree, But this may not be the scope of UIWidgets. We could create another project for this.
