### ISSUE TITLE
编辑器下图片刷新显示异常

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#66]
1.使用Unity.UIWidgets.widgets.Image.file(@"D:\UnityProjects\UIWidgets\Assets\21.jpg")加载图片时，由IDE切换回Editor等待编译完成后，图片未刷新显示，需要手动修改Inspector面板上的任意值才会触发重绘。

2.颜色叠加模式未起作用

3.是否实现了CircleAvatar等常用遮罩

unity版本：2018.3.7 f1
ide: vs2017 community

`
return
                new MaterialApp(
                    title: "Welcome to Flutter",
                    home: new Scaffold(
                        appBar: new AppBar(
                            title: new Text("Welcome to Flutter")
                            ),
                        body: new Center(
                            child: new Container(
                                child: Unity.UIWidgets.widgets.Image.file(
                                    @"D:\UnityProjects\UIWidgets\Assets\21.jpg",
                                    color: Colors.green,
                                    colorBlendMode: BlendMode.modulate
                                    ),
                                width: 500,
                                height: 400,
                                color: Colors.black
                            )
                        )
                    ));
`

**Comment by kgdev** [comment]
1. Image.file是异步加载的，所以会在后面几桢显示。Image.asset是同步加载的，直接可以显示。
2. 嗯嗯，这个还未实现。什么情况需要颜色叠加模式？
3. 这个可以用Clip widget来实现。https://medium.com/flutter-community/clipping-in-flutter-e9eaa6b1721a

**Comment by liusujin** [comment]
谢谢解答，关于颜色叠加模式主要是参考flutter进行uiwidgets学习过程中发现其未起作用。类似的还有GridView等，目前是正处于和flutter 1.0对接的阶段吗？

**Comment by kgdev** [comment]
嗯嗯 对的 有什么实际问题直接提出来 我们尽快解决

颜色叠加没啥用处 所以暂时没有实现了 :)
