### ISSUE TITLE
Console调用栈信息太长被截断&双击无法跳转到IDE

### ISSUE THREAD

**Issue by VDerGoW** [UnityTech/UIWidgets#67]
1. Console输出的调用栈信息太长被Unity截断，看不到出错的代码行信息;
2. Console中的日志双击无法跳转到IDE（Visual Studio Community 2017 和 Visual Studio Code都没能跳转）。

![image](https://user-images.githubusercontent.com/11539008/55271042-bb990e00-52e1-11e9-85fb-6c6152117641.png)

**Comment by zhuxingwei** [comment]
Console中的日志双击无法跳转到IDE 应该是由于Package目录名称的问题导致的。我这边Repro了你的这个issue并且用下述方法解决了：首先重新建一个项目，然后clone UIWidget包到 com.unity.uiwidgets 这个目录（一定要是这个目录，具体可参考GitHub上的README）。然后再把原先项目的代码和资源导入到这个新的Project。这样应该就可以解决你的问题了。

**Comment by zhuxingwei** [comment]
@VDerGoW 麻烦试试？

**Comment by VDerGoW** [comment]
正常了，谢谢！
