### ISSUE TITLE
使用TimeSpan的UI动画不能逐帧运行

### ISSUE THREAD

**Issue by VDerGoW** [UnityTech/UIWidgets#68]
使用`TimeSpan`的UI动画不能逐帧运行，例如：
在UI中添加一个`Icon`，使其在程序启动后逐渐放大。如果在点击Play按钮![image](https://user-images.githubusercontent.com/11539008/55271100-90fb8500-52e2-11e9-84b0-0bab9c684423.png)之前先点击暂停按钮![image](https://user-images.githubusercontent.com/11539008/55271102-9b1d8380-52e2-11e9-835d-5bd023bfc585.png)，使程序逐帧运行，会发现动画并没有按预期逐帧放大，而是突然变大，暂停期间动画的value没有停止增长。

**Comment by kgdev** [comment]
UIWidgets的动画是严格按照时间来的，不是按照帧数。这样保证动画按照真实时间来运行，无论帧数大小。

**Comment by kgdev** [comment]
UIWidgets的动画是严格按照时间来的，不是按照帧数。这样保证动画按照真实时间来运行，无论帧数大小。

**Comment by kgdev** [comment]
https://github.com/UnityTech/UIWidgets/pull/73
