### ISSUE TITLE
不能在异步函数的回调中 setState

### ISSUE THREAD

**Issue by Latias94** [UnityTech/UIWidgets#69]
```
NullReferenceException: Object reference not set to an instance of an object
Unity.UIWidgets.scheduler.SchedulerBinding.scheduleFrame () (at Packages/com.unity.uiwidgets/Runtime/scheduler/binding.cs:184)
Unity.UIWidgets.scheduler.SchedulerBinding.ensureVisualUpdate () (at Packages/com.unity.uiwidgets/Runtime/scheduler/binding.cs:162)
Unity.UIWidgets.widgets.WidgetsBinding._handleBuildScheduled () (at Packages/com.unity.uiwidgets/Runtime/widgets/binding.cs:108)
Unity.UIWidgets.widgets.BuildOwner.scheduleBuildFor (Unity.UIWidgets.widgets.Element element) (at Packages/com.unity.uiwidgets/Runtime/widgets/framework.cs:891)
Unity.UIWidgets.widgets.Element.markNeedsBuild () (at Packages/com.unity.uiwidgets/Runtime/widgets/framework.cs:2044)
Unity.UIWidgets.widgets.State.setState (Unity.UIWidgets.ui.VoidCallback fn) (at Packages/com.unity.uiwidgets/Runtime/widgets/framework.cs:510)
BookListState.<RequestBooks>b__2_0 (System.Object response) (at Assets/Scripts/BookListPage.cs:45)
HTTPHelper+<GetAsync>d__8`1[T].MoveNext () (at Assets/Scripts/HTTPHelper.cs:82)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:115)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```
用 HTTPClient 异步发 Get 请求，在回调函数中 setState 报上面的错误。
具体仓库在 [UIWidget-Practice](https://github.com/Latias94/UIWidget-Practice)，报错行数在 [这里](https://github.com/Latias94/UIWidget-Practice/blob/46383ce442beacd148dad946b0baf0a9f547cb1d/Assets/Scripts/BookListPage.cs#L45)。

还是说我写的姿势不对？

**Comment by VDerGoW** [comment]
Android和Unity都不允许在非主线程操作UI吧

**Comment by Latias94** [comment]
> Android和Unity都不允许在非主线程操作UI吧

在回调中写应该没问题吧？那应该怎么改呢？

**Comment by kgdev** [comment]
嗯嗯 首先你要打开debug模式, 然后会有相应的提示信息给到你.

Define UIWidgets_DEBUG
It's recommended to define the UIWidgets_DEBUG script symbol in editor, this will turn on debug assertion in UIWidgets, which will help to find potential bugs earlier. To do this: please go to Player Settings -> Other Settings -> Configuration -> Scripting Define Symbols, and add UIWidgets_DEBUG.
The symbol is for debug purpose, please remove it from your release build.

**Comment by Latias94** [comment]
> 嗯嗯 首先你要打开debug模式, 然后会有相应的提示信息给到你.
> 
> Define UIWidgets_DEBUG
> It's recommended to define the UIWidgets_DEBUG script symbol in editor, this will turn on debug assertion in UIWidgets, which will help to find potential bugs earlier. To do this: please go to Player Settings -> Other Settings -> Configuration -> Scripting Define Symbols, and add UIWidgets_DEBUG.
> The symbol is for debug purpose, please remove it from your release build.

你好，上面的报错就是加了 UIWidgets_DEBUG 后的报错信息，想问问有没有网络请求的 sample 供参考呢？

**Comment by kgdev** [comment]
Try to use "using (WindowProvider.of(BuildContext).getScope()) { ... }" to wrap your code.

BuildContext 如果在widget里面就是this.context.

**Comment by VDerGoW** [comment]
> > Android和Unity都不允许在非主线程操作UI吧
> 
> 在回调中写应该没问题吧？那应该怎么改呢？

你的回调方法是在主线程里面声明的，但是它的调用是在异步线程中调用的，所以他还是在异步中执行的。应该在主线程中写一个调用队列，异步完成时把回调塞到队列里，然后主线程一直检测队列中是否有要执行的回调，如果有，就执行，这样UI操作就回到主线程执行了。

**Comment by Latias94** [comment]
> Try to use "using (WindowProvider.of(BuildContext).getScope()) { ... }" to wrap your code.
> 
> BuildContext 如果在widget里面就是this.context.

Solved! 
Thanks for your quick response, May I ask if there has a communication group for testing UIWidgets?

**Comment by kgdev** [comment]
https://connect.unity.com/u/kevin-gu

Add me as a friend and I will add you to our wechat group.

**Comment by qingbaomeng** [comment]
@Latias94  using (WindowProvider.of(BuildContext).getScope()) { ... } 
你是用这个方案解决的吗？

**Comment by Latias94** [comment]
> @Latias94 using (WindowProvider.of(BuildContext).getScope()) { ... }
> 你是用这个方案解决的吗？

你好，我忘了... 不过你可以参考下两个官方开源应用的做法：
https://github.com/UnityTech/ConnectAppCN
https://github.com/UnityTech/DocCN
