### ISSUE TITLE
Icon有时候显示不出来

### ISSUE THREAD

**Issue by zgzcir** [UnityTech/UIWidgets#71]

**Comment by kgdev** [comment]
嗯 能具体一点吗 给一下repro step

**Comment by zgzcir** [comment]
public BottomNavigationBar BotNavbar = new BottomNavigationBar(fixedColor: Color.fromARGB(255, 0, 218, 0),
    items: new List<BottomNavigationBarItem>(){
            new BottomNavigationBarItem(
            icon: new Icon(Icons.ac_unit)
            , activeIcon: new Icon(Icons.access_alarm)
            , title: new Text("test")
            , backgroundColor: Color.fromARGB(255,37, 37, 38)
        ),
        new BottomNavigationBarItem(
            icon: new Icon(Icons.account_balance)
            , activeIcon: new Icon(Icons.access_alarm)
            , title: new Text("test")
            , backgroundColor: Color.fromARGB(255, 37, 37, 38)
        ),new BottomNavigationBarItem(
            icon: new Icon(Icons.ac_unit)
            , activeIcon: new Icon(Icons.access_alarm)
            , title: new Text("test")
            , backgroundColor: Color.fromARGB(255, 37, 37, 38)
        ),new BottomNavigationBarItem(
            icon: new Icon(Icons.ac_unit)
            , activeIcon: new Icon(Icons.access_alarm)
            , title: new Text("test")
            , backgroundColor: Color.fromARGB(255,37, 37, 38)
        )
    },
    currentIndex: 0,
    type: BottomNavigationBarType.shifting
);
        public override Widget build(BuildContext context)
        {
    
            return new Scaffold(
                appBar: new AppBar(title: new Text("WeChat"), backgroundColor: Color.fromARGB(255, 0, 122, 204))
                , body: new Container(/* color: Color.fromARGB(255, 30, 30, 30*/),
                bottomNavigationBar: BotNavbar
            );
        }
    }

**Comment by zgzcir** [comment]
抱歉原先问题太过简略。
1.
在打开实例场景Gallery后，如果代码重新编译的话，Scene中的Icon就会消失。

2.
另外像这样的代码里的icon，在unity中无法显示。
https://paste.ubuntu.com/p/fWMdFg6jsq/
因为是照着flutter的教程进行学习的，所以不知道这些代码是UIWidegts与Flutter有区别还是我代码的错误。

**Comment by kgdev** [comment]
![image](https://user-images.githubusercontent.com/6348456/55288283-dc4b8b80-53e7-11e9-8376-234a47503405.png)

要加下面这个来加载字体。

![image](https://user-images.githubusercontent.com/6348456/55288293-f6856980-53e7-11e9-87a8-55b17aa823f8.png)

**Comment by zgzcir** [comment]
十分感谢

**Comment by zgzcir** [comment]
请问这条issue可以帮我删除吗😃
