### ISSUE TITLE
UI Canvas visible on Safari but not on Chrome using WebGL

### ISSUE THREAD

**Issue by JustinFincher** [UnityTech/UIWidgets#79]
Environment:
- Unity 2018.3.11f1
- UIWidgets commit d76d75340e015215c58b2fa12c39f68ff1df25d9
- Auto Graphics API

Issue:
When exported to WebGL, my project using UIWidgets won't display the UI on Chrome (showing default Skybox), but it works well on Safari (see images below). You can visit [https://wizardly-goodall-109263.netlify.com/](https://wizardly-goodall-109263.netlify.com/) for a test. The console in Chrome didn't throw any error when loading the scene. 🤔
![image](https://user-images.githubusercontent.com/8359912/55373255-21ca9e80-5537-11e9-9fca-85565024319d.png)

Attachment:
https://www.dropbox.com/s/2ajywuu8ybbxxol/UIWidgets-Chrome-Issue-Sample.zip?dl=0

**Comment by kgdev** [comment]
Thanks @JustinFincher , we will take a look.

**Comment by JustinFincher** [comment]
@kgdev Thanks for reaching out, I have updated my project on the same link [https://wizardly-goodall-109263.netlify.com/](https://wizardly-goodall-109263.netlify.com/), this time I have added a bottom modal sheet which would be triggered by the fab button. If I click the fab button, the whole canvas would repaint but always flickers. 

![image](https://user-images.githubusercontent.com/8359912/55457567-e73b3180-561c-11e9-947e-b7b7bce253ec.png)

**Comment by kgdev** [comment]
https://github.com/UnityTech/UIWidgets/pull/88

Just had a fix, could you please try it again?

**Comment by JustinFincher** [comment]
@kgdev Lastest build with commit https://github.com/UnityTech/UIWidgets/pull/88 works flawlessly! Thank you for fixing this issue this quick 👍
