### ISSUE TITLE
打算这个月（4 月）出一份教学视频

### ISSUE THREAD

**Issue by liangxieq** [UnityTech/UIWidgets#80]

**Comment by liangxieq** [comment]
现在没有一个明确的 release 版本，也没有版本号，如果视频过时了，会对很多学生造成困扰。这个怎么解？

**Comment by kgdev** [comment]
嗯嗯 这个想法太赞了。 API基本不会变。现在是对着flutter 1.0。 我们会尽快对齐flutter 1.2
