### ISSUE TITLE
关于async/await在uiwidgets中的使用

### ISSUE THREAD

**Issue by liusujin** [UnityTech/UIWidgets#93]
在界面跳转需要异步加载的时候Navigator是否会提供异步方法，目前使用Promise时遇到一些问题，使用如下代码时快速点击界面按钮时通过snackbar返回的数据有误，必须等待上一个snackbar自己消失后再点击才不会出错。

`
using RSG;
using System.Collections;
using System.Collections.Generic;
using Unity.UIWidgets.animation;
using Unity.UIWidgets.engine;
using Unity.UIWidgets.foundation;
using Unity.UIWidgets.material;
using Unity.UIWidgets.painting;
using Unity.UIWidgets.ui;
using Unity.UIWidgets.widgets;
using UnityEngine;

namespace Utils.Model.Tutorials
{
    public class TestWidgets : UIWidgetsPanel
    {
        protected override Widget createWidget()
        {
            return new MaterialApp(
                title: "页面跳转返回数据",
                home: new FirstPage()
                );
        }
    }

    public class FirstPage : StatelessWidget
    {
        public override Widget build(BuildContext context)
        {
            return new Scaffold(
                appBar:new AppBar(title:new Text("去找东西")),
                body:new RouteButton()
                );
        }
    }

    public class RouteButton : StatelessWidget
    {
        public override Widget build(BuildContext context)
        {
            return new RaisedButton(
                onPressed: () => NavigateToFindLoli(context),
                child: new Text("找一找")
                );
        }

        private void NavigateToFindLoli(BuildContext context)
        {
            var result = Navigator.push(
                context,
                new MaterialPageRoute(builder: localContext => new Loli())
                ).Then(
                    arg => 
                    {
                        Scaffold.of(context).showSnackBar(new SnackBar(content: new Text($"{arg}")));
                    }
                );            
        }
    }

    public class Loli : StatelessWidget
    {
        public override Widget build(BuildContext context)
        {
            return new Scaffold(
                    appBar:new AppBar(
                        title:new Text("找到了什么？")
                        ),
                    body:new Center(
                        child:new Column(
                            children:new List<Widget>() {
                                new RaisedButton(
                                    child:new Text("椅子"),
                                    onPressed:() => Navigator.pop(context,"这是椅子")
                                    ),
                                new RaisedButton(
                                    child:new Text("凳子"),
                                    onPressed:() => Navigator.pop(context,"这是凳子")
                                    ),
                                new RaisedButton(
                                    child:new Text("桌子"),
                                    onPressed:() => Navigator.pop(context,"这是桌子")
                                    )
                            }
                            )
                        )
                );
        }
    }
}
`

**Comment by fzhangtj** [comment]
你好，这个问题可能是showSnackBar的使用问题。flutter 文档对showsSnackBar的说明:

> A scaffold can show at most one snack bar at a time. If this function is called while another snack bar is already visible, the given snack bar will be added to a queue and displayed after the earlier snack bars have closed.

调用showSnackBar时如果已经有snackBar了，并不会更新现有的内容，而是等待当前显示结束后再显示下一个。所以点击界面按钮时，数据其实已经正确返回了(这一点可以通过在push的Then回调里打印出arg的数值进行验证)，不过snackBar并没有立刻显示新的内容。
